import { config } from 'dotenv'
import path from 'path'
config({ path: path.resolve(__dirname, '../../.env') })

import Fastify from 'fastify'
import cors from '@fastify/cors'
import { authRoutes } from './routes/auth'
import { publishRoutes } from './routes/publish'
import { generateRoutes } from './routes/generate'

const server = Fastify({ logger: true })

server.register(cors, { origin: '*' })

server.get('/health', async () => ({ status: 'ok', service: 'glosx-api' }))

server.register(authRoutes)
server.register(publishRoutes)
server.register(generateRoutes)

server.get('/privacy', async (request, reply) => {
  reply.type('text/html')
  return '<html><body><h1>GlosX Privacy Policy</h1><p>GlosX does not store passwords or financial data. We do not sell or share your information. Tokens are stored only on your device. Contact: GlosX@outlook.com</p></body></html>'
})

server.get('/terms', async (request, reply) => {
  reply.type('text/html')
  return '<html><body><h1>GlosX Terms</h1><p>By using GlosX you agree to our terms. Content is generated by AI - review before publishing. You are responsible for what you publish.</p></body></html>'
})

const start = async () => {
  try {
    await server.listen({ port: 3000, host: '0.0.0.0' })
    console.log('glosx API corriendo en http://localhost:3000')
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

start()
