import { config } from 'dotenv'
import path from 'path'
config({ path: path.resolve(__dirname, '../../.env') })

import Fastify from 'fastify'
import cors from '@fastify/cors'
import { authRoutes } from './routes/auth'
import { publishRoutes } from './routes/publish'
import { generateRoutes } from './routes/generate'

const server = Fastify({ logger: true })

server.register(cors, { origin: '*' })

server.get('/health', async () => ({ status: 'ok', service: 'glosx-api' }))

server.get('/', async (request, reply) => {
  reply.type('text/html')
  return `<html><head><title>GlosX - Your voice, on every network</title></head><body style="font-family:sans-serif;max-width:600px;margin:50px auto;padding:20px"><h1>GlosX</h1><p>Transform your ideas into social media content for 10 platforms using AI.</p><p>Available on iOS and Android.</p><a href="/privacy">Privacy Policy</a> | <a href="/terms">Terms</a></body></html>`
})

server.get('/privacy', async (request, reply) => {
  reply.type('text/html')
  return '<html><body><h1>GlosX Privacy Policy</h1><p>GlosX does not store passwords or financial data. We do not sell or share your information. Tokens are stored only on your device. Contact: GlosX@outlook.com</p></body></html>'
})

server.get('/terms', async (request, reply) => {
  reply.type('text/html')
  return '<html><body><h1>GlosX Terms</h1><p>By using GlosX you agree to our terms. Content is generated by AI - review before publishing. You are responsible for what you publish.</p></body></html>'
})

server.register(authRoutes)
server.register(publishRoutes)
server.register(generateRoutes)

const start = async () => {
  try {
    const port = Number(process.env.PORT) || 3000
    await server.listen({ port, host: '0.0.0.0' })
    console.log(`glosx API corriendo en http://localhost:${port}`)
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

start()
