import { FastifyInstance } from 'fastify'
import { generateContent, generateContentForPlatform } from '../services/ai.service'

export async function generateRoutes(server: FastifyInstance) {
  server.post('/generate', async (request, reply) => {
    const { input, styleProfile } = request.body as { input: string; styleProfile?: string }
    if (!input || input.trim().length === 0) {
      return reply.status(400).send({ error: 'input requerido' })
    }
    if (input.trim().length < 5) {
      return reply.status(400).send({ error: 'idea muy corta, escribí un poco más' })
    }
    return generateContent(input.trim(), styleProfile)
  })

  server.post('/generate-single', async (request, reply) => {
    const { platform, input, tone, voiceProfile } = request.body as {
      platform: string
      input: string
      tone?: string
      voiceProfile?: string
    }
    if (!platform || !input || input.trim().length === 0) {
      return reply.status(400).send({ error: 'platform e input son requeridos' })
    }
    try {
      const content = await generateContentForPlatform(platform, input.trim(), tone, voiceProfile)
      return { platform, content }
    } catch (error: any) {
      console.error(`Error generando ${platform}:`, error.message)
      return reply.status(500).send({ error: `Error generando contenido para ${platform}` })
    }
  })

  server.post('/generate-extra', async (request, reply) => {
    const { platform, topic, baseContent, lang } = request.body as any
    try {
      const platformRules: Record<string, string> = {
        WhatsApp: lang === 'es'
          ? 'Mensaje directo y personal, como si se lo mandaras a un amigo. Podés usar emojis con criterio. Máximo 3 párrafos cortos.'
          : 'Direct and personal message, like texting a friend. Emojis allowed. Max 3 short paragraphs.',
        Telegram: lang === 'es'
          ? 'Tono informativo pero cercano. Puede ser algo más largo que WhatsApp. Sin hashtags.'
          : 'Informative but friendly tone. Can be slightly longer than WhatsApp. No hashtags.',
        TikTok: lang === 'es'
          ? 'Texto para video corto. Gancho en la primera línea, energético, usa emojis y lenguaje joven. Máximo 150 caracteres.'
          : 'Short video caption. Strong hook, energetic, emojis, youth language. Max 150 chars.',
        Facebook: lang === 'es'
          ? 'Tono cálido y conversacional. Puede ser más largo. Termina con una pregunta para generar interacción.'
          : 'Warm and conversational. Can be longer. End with a question to drive engagement.',
        Pinterest: lang === 'es'
          ? 'Descripción visual e inspiracional. Enfocada en el estilo de vida. 2-3 oraciones + hashtags relevantes.'
          : 'Visual and inspirational description. Lifestyle-focused. 2-3 sentences + relevant hashtags.',
        LinkedIn: lang === 'es'
          ? 'Tono profesional pero humano. Insight o aprendizaje concreto. Termina con pregunta al lector. 150-300 palabras.'
          : 'Professional but human tone. Concrete insight or learning. End with a question. 150-300 words.',
      }
      const rules = platformRules[platform] || (lang === 'es' ? `Adaptalo para ${platform} con su tono típico.` : `Adapt it for ${platform} with its typical tone.`)
      const prompt = lang === 'es'
        ? `Sos la voz detrás de GlosX. Escribís como una persona real, no una máquina.
Tenés este contenido sobre "${topic}": "${baseContent}".
Adaptalo para ${platform}. Reglas: ${rules}
Solo devolvé el texto adaptado, sin explicaciones.`
        : `You are the voice behind GlosX. You write like a real person, not a machine.
You have this content about "${topic}": "${baseContent}".
Adapt it for ${platform}. Rules: ${rules}
Return only the adapted text, no explanations.`
      const { default: Anthropic } = await import('@anthropic-ai/sdk')
      const client = new Anthropic()
      const message = await client.messages.create({
        model: 'claude-opus-4-7',
        max_tokens: 500,
        messages: [{ role: 'user', content: prompt }],
      })
      const text = message.content[0].type === 'text' ? message.content[0].text : baseContent
      reply.send({ content: text.trim() })
    } catch (e: any) {
      console.error('generate-extra error:', e.message)
      reply.send({ content: baseContent })
    }
  })


  fastify.get('/privacy', async (request, reply) => {
    reply.type('text/html')
    return '<html><body><h1>GlosX Privacy Policy</h1><p>GlosX does not store passwords or financial data. We do not sell or share your information. Tokens are stored only on your device. Contact: GlosX@outlook.com</p></body></html>'
  })

  fastify.get('/terms', async (request, reply) => {
    reply.type('text/html')
    return '<html><body><h1>GlosX Terms</h1><p>By using GlosX you agree to our terms. Content is generated by AI - review before publishing. You are responsible for what you publish.</p></body></html>'
  })
}